# -*- coding: utf-8 -*-
"""NLP_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBaNZHBtMIknwFYlUsDIG4zg96DHZYDR

# # 🎬 NLP-Based Sentiment Analysis of Movie Reviews

### Using TF-IDF and Logistic Regression

This project develops a Natural Language Processing (NLP) system
to classify IMDb movie reviews as Positive or Negative.

The project uses text preprocessing and TF-IDF feature extraction
to convert reviews into numerical features. Logistic Regression is
then used to classify the reviews based on their sentiment.

## 1. Importing Required Libraries

In this step, we import the Python libraries required for data
processing, text preprocessing, machine learning, visualization,
and model evaluation.

- Pandas and NumPy → Data handling
- Matplotlib and Seaborn → Data visualization
- Regular Expressions (re) → Text cleaning
- Scikit-learn → Machine learning, TF-IDF, and evaluation
"""

# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("Libraries imported successfully!")

"""## 2. Loading the Dataset

The IMDb movie review dataset is loaded using Pandas.

The dataset contains movie reviews and their corresponding sentiment
labels. Each review is classified as either Positive or Negative.
"""

# Load the IMDb dataset

df = pd.read_csv("/content/IMDB Dataset.csv", on_bad_lines='skip')

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

"""## 3. Exploring the Dataset

Before building the model, the dataset is explored to understand
its structure, columns, number of records, and sentiment distribution.

This helps us identify the available features and check whether
the positive and negative classes are reasonably balanced.
"""

# Display the first 5 rows

df.head()

# Display dataset information

df.info()

# Count the number of positive and negative reviews

print(df["sentiment"].value_counts())

# Visualize sentiment distribution

plt.figure(figsize=(6, 4))

sns.countplot(x="sentiment", data=df)

plt.title("Distribution of Sentiments")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")

plt.show()

"""## 4. Text Preprocessing

Raw movie reviews may contain HTML tags, uppercase letters,
punctuation, and unnecessary spaces.

The preprocessing function cleans the reviews by:

1. Converting text to lowercase
2. Removing HTML tags
3. Removing unnecessary non-alphabetic characters
4. Removing extra spaces

This produces cleaner text for the NLP model.
"""

# Text preprocessing function

def clean_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text


print("Text preprocessing function created successfully!")

# Test the preprocessing function

sample_text = "<br />This movie was AMAZING!!! I really loved it!!!"

cleaned_text = clean_text(sample_text)

print("Original text:")
print(sample_text)

print("\nCleaned text:")
print(cleaned_text)

"""### Applying the Preprocessing Function

The `clean_text()` function is applied to every review in the
dataset. The cleaned reviews are stored in a new column called
`cleaned_review`, while the original reviews are preserved.
"""

# Apply text preprocessing to all reviews

df["cleaned_review"] = df["review"].apply(clean_text)

print("Text preprocessing completed!")

# Compare original and cleaned reviews

df[["review", "cleaned_review", "sentiment"]].head()

# Check for missing values

print(df.isnull().sum())

"""## 5. Encoding Sentiment Labels

Machine learning models work with numerical values, so the text
sentiment labels are converted into numbers.

- Positive → 1
- Negative → 0

This numerical representation is used as the target variable
during model training.
"""

# Convert sentiment labels into numerical values

df["label"] = df["sentiment"].map({
    "positive": 1,
    "negative": 0
})

print(df[["sentiment", "label"]].head())

# Define input features and target labels

X = df["cleaned_review"]
y = df["label"]

print("Number of reviews:", len(X))
print("Number of labels:", len(y))

"""## 6. Splitting the Dataset

The dataset is divided into training and testing sets.

- 80% of the data is used for training.
- 20% is used for testing.

The model learns patterns from the training data and is then
evaluated on unseen test data.
"""

# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

"""## 7. TF-IDF Feature Extraction

Machine learning models cannot directly understand raw text.
Therefore, the cleaned reviews are converted into numerical
features using TF-IDF (Term Frequency-Inverse Document Frequency).

TF-IDF gives higher importance to words that are useful for
distinguishing between documents while reducing the importance
of very common words.

A maximum of 5,000 features is used to keep the feature space
manageable.
"""

# Create TF-IDF vectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

print("TF-IDF vectorizer created successfully!")

# Learn vocabulary from training data and transform the training reviews

X_train_tfidf = tfidf.fit_transform(X_train)

print("TF-IDF transformation completed for training data!")
print("Training TF-IDF shape:", X_train_tfidf.shape)

# Transform the test reviews using the same TF-IDF vocabulary

X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF transformation completed for testing data!")
print("Testing TF-IDF shape:", X_test_tfidf.shape)

# Display the shape and a small portion of the TF-IDF matrix

print("Number of training reviews:", X_train_tfidf.shape[0])
print("Number of TF-IDF features:", X_train_tfidf.shape[1])

print("\nFirst review - first 20 TF-IDF values:")
print(X_train_tfidf[0].toarray()[0][:20])

# Display some TF-IDF vocabulary words

feature_names = tfidf.get_feature_names_out()

print("First 50 TF-IDF features:")
print(feature_names[:50])

"""## 8. Training the Logistic Regression Model

Logistic Regression is used as the classification algorithm for
this project.

The model learns the relationship between the TF-IDF features
and the sentiment labels from the training data.

After training, the model can predict whether a new movie review
is Positive or Negative.
"""

# Create the Logistic Regression model

model = LogisticRegression(max_iter=1000)

print("Logistic Regression model created successfully!")

# Train the model

model.fit(X_train_tfidf, y_train)

print("Model training completed successfully!")

"""## 9. Making Predictions

After training, the model is used to predict the sentiment of
the unseen test reviews.

The predicted labels are stored in `y_pred` and are compared
with the actual labels to evaluate model performance.
"""

# Predict sentiment for test data

y_pred = model.predict(X_test_tfidf)

print("Predictions generated successfully!")
print("Number of predictions:", len(y_pred))

"""## 10. Model Evaluation

The trained model is evaluated using four important classification
metrics:

- Accuracy → Overall percentage of correct predictions
- Precision → Correctness of positive predictions
- Recall → Ability to identify actual positive reviews
- F1-Score → Balance between precision and recall

These metrics provide a more complete understanding of model
performance.
"""

# Calculate evaluation metrics

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Model Evaluation Results")
print("------------------------")
print("Accuracy :", round(accuracy * 100, 2), "%")
print("Precision:", round(precision * 100, 2), "%")
print("Recall   :", round(recall * 100, 2), "%")
print("F1-Score :", round(f1 * 100, 2), "%")

"""## 11. Classification Report

The classification report provides precision, recall, F1-score,
and support for each sentiment class separately.

This helps us understand how well the model performs for both
Positive and Negative reviews.
"""

# Display detailed classification report

print(classification_report(
    y_test,
    y_pred,
    target_names=["Negative", "Positive"]
))

"""## 12. Confusion Matrix

A confusion matrix shows the number of correct and incorrect
predictions for each sentiment class.

It contains:

- True Positive (TP)
- True Negative (TN)
- False Positive (FP)
- False Negative (FN)

This helps us understand the types of errors made by the model.
"""

# Create confusion matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=["Negative", "Positive"],
    yticklabels=["Negative", "Positive"]
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Sentiment")
plt.ylabel("Actual Sentiment")

plt.show()

"""## 15. Results Table

A results table is created to present the performance of the
sentiment analysis model using Accuracy, Precision, Recall,
and F1-Score.

This provides a clear summary of the model's performance.
"""

# Create a results table

results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-Score"],
    "Score": [
        accuracy,
        precision,
        recall,
        f1
    ]
})

results["Score"] = results["Score"].round(4)

results

"""## 16. Testing the Model with New Reviews

The trained model is tested using new movie reviews that were
not part of the training process.

Each review is cleaned using the same preprocessing function
and converted into TF-IDF features. The trained Logistic
Regression model then predicts whether each review is Positive
or Negative.
"""

# Test the model with new reviews

new_reviews = [
    "This movie was absolutely fantastic and I loved every minute of it.",
    "The movie was boring and a complete waste of time.",
    "Amazing acting and a wonderful story.",
    "I hated this movie. It was extremely disappointing."
]

# Clean the new reviews
cleaned_reviews = [clean_text(review) for review in new_reviews]

# Convert the reviews into TF-IDF features
new_reviews_tfidf = tfidf.transform(cleaned_reviews)

# Predict sentiment
predictions = model.predict(new_reviews_tfidf)

# Display predictions
for review, prediction in zip(new_reviews, predictions):
    sentiment = "Positive" if prediction == 1 else "Negative"

    print("Review:", review)
    print("Predicted Sentiment:", sentiment)
    print("-" * 70)

"""## 17. Installing Gradio

Gradio is used to create a simple interactive user interface for
the trained sentiment analysis model. It allows users to enter
their own movie reviews and receive a sentiment prediction.
"""

!pip install gradio -q

import re

# Text preprocessing function

def clean_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

print("clean_text function is ready!")

# Test the trained model directly

test_reviews = [
    "This movie was absolutely fantastic. The acting was brilliant!",
    "I loved this movie. It was amazing and wonderful.",
    "This was the worst movie I have ever seen. It was terrible and boring."
]

for review in test_reviews:
    cleaned = clean_text(review)
    features = tfidf.transform([cleaned])

    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0]

    print("Review:", review)
    print("Cleaned:", cleaned)
    print("Prediction:", "Positive" if prediction == 1 else "Negative")
    print("Probabilities:", probability)
    print("-" * 80)

"""# 19. Interactive Sentiment Analysis Application

A Gradio-based interactive application is developed to demonstrate
the practical use of the trained NLP model.

The user can enter a movie review into the text box. The review
is preprocessed and converted into TF-IDF features before being
passed to the trained Logistic Regression model.

The application displays the predicted sentiment along with
the confidence score.
"""

import gradio as gr

# Function to predict sentiment
def predict_sentiment(review):
    if not review.strip():
        return "Please enter a movie review."

    # Clean the input text
    cleaned_review = clean_text(review)

    # Convert text into TF-IDF features
    review_tfidf = tfidf.transform([cleaned_review])

    # Predict sentiment
    prediction = model.predict(review_tfidf)[0]

    # Get prediction probability
    probability = model.predict_proba(review_tfidf)[0]

    if prediction == 1:
        sentiment = "Positive"
        confidence = probability[1] * 100
    else:
        sentiment = "Negative"
        confidence = probability[0] * 100

    return f"Sentiment: {sentiment}\nConfidence: {confidence:.2f}%"


# Create the Gradio interface
app = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(
        lines=5,
        placeholder="Enter a movie review here...",
        label="Movie Review"
    ),
    outputs=gr.Textbox(
        label="Prediction"
    ),
    title="🎬 IMDb Movie Review Sentiment Analyzer",
    description="Enter a movie review to predict whether it is Positive or Negative.",
    examples=[
        ["This movie was absolutely fantastic. The acting was brilliant!"],
        ["The movie was boring and disappointing. I hated it."],
        ["An amazing story with excellent performances."]
    ]
)

# Launch the application
app.launch()

"""# Project Completed

The IMDb movie review sentiment analysis project was successfully implemented using text preprocessing, TF-IDF feature extraction, and Logistic Regression.

The model was evaluated using Accuracy, Precision, Recall, F1-Score, and Confusion Matrix and was successfully integrated into an interactive Gradio application.
"""